apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: document-service
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - kafka.yaml
  - kafka-topics-job.yaml
  - deployment.yaml
  - worker-deployment.yaml
  - service.yaml
  - hpa.yaml
  - worker-hpa.yaml
  - migration-job.yaml
